import { Flex, VStack } from '@chakra-ui/react';
import { motion } from 'framer-motion';
import Head from 'next/head';
import React from 'react';

import Footer from '../Footer';
import { Header } from '../Header';

interface LayoutProps {
  children: React.ReactNode;
}
const Layout = ({ children }: LayoutProps) => {
  return (
    <>
      <VStack h={'100vh'} spacing={'0'} width={'88%'} margin={'auto'}>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <Flex as={'header'} w='full' maxH={16} h='full' mt={'80px'}>
          <Header />
        </Flex>
        <Flex flex={1} w='full'>
          {children}
        </Flex>
        <Flex as={motion.footer} w='full' pt={12}>
          <Footer />
        </Flex>
      </VStack>
    </>
  );
};

export default Layout;
